services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: confession-wall-admin
    ports:
      - "5173:5173"  # vite 开发服务器默认端口
    restart: always
    networks:
      - confession-network

networks:
  confession-network:
    driver: bridge 